[programs.devnet]
solana_tweet = "6bFCwUtVEv2P1wbe7Xozgi9ooyauXEQWmy6DnCjrUVNv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/solana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
